# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170617_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.URLField(default='null'),
        ),
    ]
