# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_place_hobby_tages'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Photo_Post',
            fields=[
                ('photopostid', models.AutoField(primary_key=True, serialize=False)),
                ('photoposttext', models.CharField(max_length=5000)),
                ('ratings', models.FloatField(default=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(default='', to='posts.Photos')),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Photo_Post_Comment',
            fields=[
                ('photocommentid', models.AutoField(primary_key=True, serialize=False)),
                ('photocomment', models.CharField(max_length=5000)),
                ('photopostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People_Photo_Post')),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Photo_Post_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='none', max_length=1000)),
                ('report', models.CharField(blank=True, default='none', max_length=20)),
                ('photopostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People_Photo_Post')),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Trips',
            fields=[
                ('tripid', models.AutoField(primary_key=True, serialize=False)),
                ('traveling_from', models.CharField(max_length=1000)),
                ('traveling_to', models.CharField(max_length=1000)),
                ('travel_starting_date', models.DateField()),
                ('travel_ending_date', models.DateField()),
                ('nooftravelerscurrent', models.IntegerField()),
                ('nooftravelersrequired', models.IntegerField()),
                ('preferences', models.CharField(max_length=5000)),
                ('trip_planning', models.CharField(max_length=5000)),
                ('expenses_details', models.CharField(max_length=2000)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now=True)),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Trips_Comment',
            fields=[
                ('tripcommentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=5000)),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('tripid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People_Trips')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Trips_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='none', max_length=1000)),
                ('report', models.CharField(blank=True, default='none', max_length=20)),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('tripid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People_Trips')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
    ]
