# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170630_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people_photo_post',
            old_name='photos',
            new_name='photosimg',
        ),
    ]
