# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_join_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_article',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
