# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_people_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_article',
            name='article_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
