# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_people_article_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_article_comment',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='people_article_status',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='people_photo_post_comment',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='people_photo_post_status',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='people_trips_comment',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='people_trips_status',
            name='placeid',
        ),
    ]
