# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170702_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_Tips',
            fields=[
                ('tipid', models.AutoField(primary_key=True, serialize=False)),
                ('tiptitle', models.CharField(blank=True, max_length=500, null=True)),
                ('tipdetails', models.CharField(max_length=1000)),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place')),
                ('tipuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='People_Tips_Status',
            fields=[
                ('tipstatusid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, max_length=10)),
                ('report', models.CharField(blank=True, default='none', max_length=50)),
                ('tipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People_Tips')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.People')),
            ],
        ),
    ]
