# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_people_tips_people_tips_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_table',
            name='post_tip',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.People_Tips'),
        ),
        migrations.AddField(
            model_name='people_tips',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
