# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170703_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverid', to='posts.People')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderid', to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=5000, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.conversation')),
                ('msgreceiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgreceiverid', to='posts.People')),
                ('msgsenderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgsenderid', to='posts.People')),
            ],
        ),
    ]
