# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='manytomanyanswerstatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Answer_Status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyarticlestatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Article_Status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanypeopleid',
            field=models.ManyToManyField(default='', null=True, related_name='_people_manytomanypeopleid_+', to='posts.People'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyphotopoststatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Photo_Post_Status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyplaceid',
            field=models.ManyToManyField(default='', null=True, to='posts.Place'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyquestionstatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Question_Status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyreviewstatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.Review_place_status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanytipstatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Tips_Status'),
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanytripstatusid',
            field=models.ManyToManyField(default='', null=True, to='posts.People_Trips_Status'),
        ),
    ]
