# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_people_article_hobbytags'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='point',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
