# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_people_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='manytomanyquestionstatusid',
            field=models.ManyToManyField(to='posts.People_Question_Status'),
        ),
    ]
