# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20170705_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='manytomanyanswerstatusid',
            field=models.ManyToManyField(null=True, to='posts.People_Answer_Status'),
        ),
        migrations.AlterField(
            model_name='people',
            name='manytomanyarticlestatusid',
            field=models.ManyToManyField(null=True, to='posts.People_Article_Status'),
        ),
        migrations.AlterField(
            model_name='people',
            name='manytomanyphotopoststatusid',
            field=models.ManyToManyField(null=True, to='posts.People_Photo_Post_Status'),
        ),
        migrations.AlterField(
            model_name='people',
            name='manytomanyreviewstatusid',
            field=models.ManyToManyField(null=True, to='posts.Review_place_status'),
        ),
        migrations.AlterField(
            model_name='people',
            name='manytomanytipstatusid',
            field=models.ManyToManyField(null=True, to='posts.People_Tips_Status'),
        ),
        migrations.AlterField(
            model_name='people',
            name='manytomanytripstatusid',
            field=models.ManyToManyField(null=True, to='posts.People_Trips_Status'),
        ),
    ]
