# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20170707_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placetype', models.CharField(max_length=2)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_like_type', to='posts.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='people_follow',
            name='followid',
        ),
        migrations.RemoveField(
            model_name='people_follow',
            name='followingid',
        ),
        migrations.DeleteModel(
            name='People_Follow',
        ),
        migrations.AddField(
            model_name='people',
            name='manytomanyplacetype',
            field=models.ManyToManyField(default='', null=True, to='posts.Place_type'),
        ),
    ]
