# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20170715_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='manytomanyplacetype',
            field=models.ManyToManyField(default='', null=True, to='posts.Place_Type'),
        ),
    ]
