# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20170715_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place_type',
            new_name='PlaceType',
        ),
    ]
