# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20170715_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Place'),
        ),
    ]
