# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import geosimple.fields
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20170715_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hobby_tages',
        ),
        migrations.AddField(
            model_name='place',
            name='locations',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='places',
            field=models.ManyToManyField(default='', to='posts.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='Summit_Coordinates',
            field=geosimple.fields.GeohashField(db_index=True, max_length=12),
        ),
    ]
