# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20170718_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='places',
        ),
    ]
