# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_people_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='commonly_visited_from',
            field=models.CharField(default='Let us know if you have been here..', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='govt_guidelines',
            field=models.CharField(default='Let us know if you have been here..', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='open_timings',
            field=models.CharField(default='Let us know if you have been here..', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='popular_route',
            field=models.CharField(default='Let us know if you have been here..', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='weather_details',
            field=models.CharField(default='Let us know if you have been here..', max_length=200),
        ),
    ]
