# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_place_title_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='hobby_tages',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
    ]
