# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_place_hobby_tages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hobby_tages',
        ),
    ]
