# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_remove_place_hobby_tages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='commonly_visited_from',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='govt_guidelines',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_timings',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='popular_route',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='weather_details',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
    ]
