# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20170726_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='duration_of_visit',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
    ]
