# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_place_duration_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='duration_of_visit',
            field=models.CharField(default='Let us know if you have been here..', max_length=50),
        ),
    ]
