# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20170726_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='languages_spoken',
            field=models.TextField(default='Let us know if you have been here..'),
        ),
    ]
