# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_place_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_photo_post',
            name='photoposttext',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
