# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_auto_20170727_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='adminpoint',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
