# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_people_adminpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title_location',
            field=models.CharField(default='fill it', max_length=120),
        ),
    ]
