# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_adminlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='aboutme',
            field=models.CharField(default='The user is yet to update', max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='best_time',
            field=models.TextField(default='Edit if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(default='Enter trek type, e.g. Himalyan Trek, Western Ghats Trek etc', max_length=400),
        ),
        migrations.AlterField(
            model_name='place',
            name='exploration_spots',
            field=models.TextField(default='Edit if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='govt_guidelines',
            field=models.TextField(default='Edit if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='highest_altitude',
            field=models.CharField(default='Edit if you have been here..', max_length=120),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_timings',
            field=models.TextField(default='Edit if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(default='Edit if you have been here..', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='weather_details',
            field=models.TextField(default='Edit if you have been here..'),
        ),
        migrations.AlterField(
            model_name='place',
            name='wildlife_reserve',
            field=models.CharField(default='Edit if you have been here..', max_length=120),
        ),
    ]
