# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_auto_20170802_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.URLField(default='/media/avt.png'),
        ),
    ]
