# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_join_table_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_table',
            name='data',
        ),
    ]
