# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_user_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_people', to='posts.People')),
            ],
        ),
    ]
