# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_table',
            name='post_photo',
        ),
    ]
