# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_remove_join_table_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_table',
            name='post_photo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.People_Photo_Post'),
        ),
    ]
