# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0005_place_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hobbytag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='null', max_length=255)),
                ('locations', location_field.models.plain.PlainLocationField(max_length=63)),
                ('places', models.ManyToManyField(default='', to='posts.Place')),
            ],
        ),
        migrations.AddField(
            model_name='hobbytag',
            name='statename',
            field=models.ManyToManyField(to='search_app.states'),
        ),
    ]
