# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 19:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_states_location'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='states',
            managers=[
                ('dfilter', django.db.models.manager.Manager()),
            ],
        ),
    ]
