# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20170624_1929'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='states',
            managers=[
            ],
        ),
    ]
