# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 20:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_auto_20170624_1933'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='states',
            managers=[
                ('objectss', django.db.models.manager.Manager()),
            ],
        ),
    ]
