# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_auto_20170624_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbytag',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
