# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_place_hobby_tages'),
        ('search_app', '0007_hobbytag_extra_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbytag',
            name='extra_tags',
        ),
        migrations.AddField(
            model_name='extra_tag',
            name='hobbytages',
            field=models.ManyToManyField(default='', to='search_app.hobbytag'),
        ),
        migrations.AddField(
            model_name='extra_tag',
            name='statetages',
            field=models.ManyToManyField(default='', to='search_app.states'),
        ),
        migrations.AddField(
            model_name='hobbytag',
            name='places',
            field=models.ManyToManyField(default='', to='posts.Place'),
        ),
    ]
