# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_auto_20170802_1301'),
        ('search_app', '0008_auto_20170626_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_tag',
            name='hobbytages',
        ),
        migrations.RemoveField(
            model_name='extra_tag',
            name='statetages',
        ),
        migrations.AddField(
            model_name='extra_tag',
            name='places',
            field=models.ManyToManyField(default='', to='posts.Place'),
        ),
    ]
