# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0009_auto_20170902_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_tag',
            name='hobbytages',
            field=models.ManyToManyField(default='', to='search_app.hobbytag'),
        ),
    ]
