# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=120, null=True)),
                ('ex_info', models.TextField(default='', null=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_place', to='posts.Place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_people', to='posts.People')),
            ],
        ),
        migrations.CreateModel(
            name='Place_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=120, null=True)),
                ('category', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=120)),
                ('Cover_Pic', models.FileField(blank=True, null=True, upload_to='')),
                ('Video_Link', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('trail_highlights', models.TextField(default='', null=True)),
                ('highest_altitude', models.CharField(default='', max_length=120, null=True)),
                ('about_the_trek', models.TextField(default='', null=True)),
                ('access_time', models.TextField(default='', null=True)),
                ('best_time', models.TextField(default='', null=True)),
                ('Exploration_Spots', models.TextField(default='', null=True)),
                ('trek_duration', models.CharField(default='', max_length=120, null=True)),
                ('trek_length', models.CharField(default='', max_length=120, null=True)),
                ('endurance_level', models.CharField(default='', max_length=120, null=True)),
                ('difficulty', models.CharField(default='', max_length=120, null=True)),
                ('route_to_base_camp', models.CharField(default='', max_length=120, null=True)),
                ('route_details', models.TextField(default='', null=True)),
                ('base_village', models.CharField(default='', max_length=120, null=True)),
                ('trek_route', models.TextField(default='', null=True)),
                ('wildlife_reserve', models.CharField(default='', max_length=120, null=True)),
                ('food_availability', models.TextField(default='', null=True)),
                ('water_availability', models.TextField(default='', null=True)),
                ('shade_availability', models.TextField(default='', null=True)),
                ('accomodation', models.TextField(default='', null=True)),
                ('police_station', models.CharField(default='', max_length=200, null=True)),
                ('atm', models.CharField(default='', max_length=200, null=True)),
                ('mobile_signals', models.CharField(default='', max_length=200, null=True)),
                ('bus_stand', models.CharField(default='', max_length=200, null=True)),
                ('railway_station', models.CharField(default='', max_length=200, null=True)),
                ('airport', models.CharField(default='', max_length=200, null=True)),
                ('local_govt_authority', models.TextField(default='')),
                ('Summit_Coordinates', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Base_Village1_Coordinates', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Base_Village2_Coordinates', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, default='', null=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tem_place', to='posts.Place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_people', to='posts.People')),
            ],
        ),
    ]
