# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edite_data', '0002_auto_20170729_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_temp',
            name='state',
            field=models.CharField(default='Let us know if you have been here..', max_length=50),
        ),
    ]
