# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edite_data', '0006_new_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_place',
            name='place_id',
        ),
    ]
