# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edite_data', '0008_user_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_record',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='user_record',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='user_record',
        ),
    ]
