# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 07:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edite_data', '0009_auto_20170916_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_place',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
